### ISSUE TITLE
Extend workflow manager to accommodate data acquisition and file management

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/coal-sds#18]
Post 0.1 release, once we have stable stand alone services for data acquisition, file management and workflow management (running pycoal tasks), our workflow management should be extended to automate data acquisition and file management. This is a huge move towards the creation of an end-to-end science data system processing capability.

**Comment by lewismc** [comment]
This issue requires us to investigate the following
```
  Action:
    Id: TriggerPostIngestWorkflow
    Description: Triggers workflow event with the name [ProductType]Ingest
    Phases: [postIngestSuccess]
```
Essentially what we want to do here is add the action to ```crawlctl``` as follows

```
--actionIds DeleteDataFile TriggerPostIngestWorkflow
```
We also need to add the workflow manager URL e.g.
```
--workflowMgrUrl http://localhost:9001
```
Once we configure the workflow manager, this will [send an event](https://github.com/apache/oodt/blob/master/crawler/src/main/java/org/apache/oodt/cas/crawl/action/WorkflowMgrStatusUpdate.java#L56) and will enable us to kick off a workflow :)
